// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function BlockContact(arg1) {
  return window['go']['main']['App']['BlockContact'](arg1);
}

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function GetChatSummaries() {
  return window['go']['main']['App']['GetChatSummaries']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetIdentity() {
  return window['go']['main']['App']['GetIdentity']();
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function MarkAsRead(arg1) {
  return window['go']['main']['App']['MarkAsRead'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function UnblockContact(arg1) {
  return window['go']['main']['App']['UnblockContact'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
