// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<domain.Contact>;

export function BlockContact(arg1:string):Promise<void>;

export function ClearHistory(arg1:string):Promise<void>;

export function DeleteContact(arg1:string):Promise<void>;

export function GetChatSummaries():Promise<Array<domain.ChatSummary>>;

export function GetContacts():Promise<Array<domain.Contact>>;

export function GetIdentity():Promise<domain.User>;

export function GetMessages(arg1:string,arg2:number,arg3:string):Promise<Array<domain.Message>>;

export function GetSettings():Promise<domain.Settings>;

export function MarkAsRead(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<domain.Message>;

export function UnblockContact(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string):Promise<void>;

export function UpdateSettings(arg1:domain.Settings):Promise<void>;
